CREATE OR REPLACE PROCEDURE LIFECYCLE.GLACIER.PURGE_DATA("ENDDATE" DATE)
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    DELETE FROM LIFECYCLE.DATA.EXAMPLE_DATA WHERE EVT_DATE < :ENDDATE;
    RETURN ''Done'';
END';


create or replace task LIFECYCLE.GLACIER.PURGE_EXAMPLE_DATA
	schedule='USING CRON 0 0 * * * UTC'
	USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL'
	as BEGIN
    CALL PURGE_DATA(DATEADD(day, -30, CURRENT_DATE()));
END;